# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test"
client_id = "be87cedb9a64fb58695bcee667823375"
application_url = "https://permissions-dave-merry-diamonds.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://permissions-dave-merry-diamonds.trycloudflare.com/auth/callback",
  "https://permissions-dave-merry-diamonds.trycloudflare.com/auth/shopify/callback",
  "https://permissions-dave-merry-diamonds.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "adesso-dev-shop.myshopify.com"
